<MyGrid>
     equ :equ
     GridLayout:
          cols:1
          size: root.width -200 , root.height -200
          pos: 100,100


          GridLayout:
               cols:2

               Label:
                    text:"Enter The Equation: "
               TextInput:
                    id:equ
                    multiline:False

          Button:
               text: "Answer"
               on_press: root.sum()


               
